name: Build and deploy GH Pages

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@master
        env:
          # Target branch
          PAGES_BRANCH: gh-pages
          # Using automatic token from GitHub
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
